### ISSUE TITLE
Unable to generate events using SDK 4.1.0

### ISSUE THREAD

**Issue by nithinnambiar** [jpotts/alfresco-kafka#1]

**Comment by jpotts** [comment]
This project does not claim to be compatible with SDK 4.1.0.

You are welcome to upgrade it to work with 4.1.0, but that may require changes to the code and dependencies to get it working. I haven't tried to get it to work with SDK 4.x but it should not take that much effort.

I will leave this open until someone is able to upgrade it to the latest SDK.

**Comment by abhinavmishra14** [comment]
@jpotts Saw this issue in the evening, I already have sdk4.1 converted version of source code, did it few months ago but did not checked-in. Sharing it via PR.

**Comment by jpotts** [comment]
The project is now in an SDK 4.1.0 project structure. This means that running it using run.sh and Docker as-is will not communicate with a Kafka broker installed on localhost. I'll open a new issue to track the need to address this, maybe by adding a Kafka image to docker-compose.yml for testing purposes.
